version: "3.8"

services:
  ikcv:
    image: ukrgerri4/ikcv:${TAG:-latest}
    container_name: ikcv
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    volumes:
        - ikcv_nm:/app/node_modules
    # stdin_open: true
    # tty: true
volumes: 
  ikcv_nm: