version: "3.8"
services:
  ikcv_js:
    build: 
      context: .
      dockerfile: Dockerfile.Development
    container_name: ikcv_js_dev
    ports:
      - "4200:4200"
    volumes:
      - type: bind
        source: ./
        target: /app
    entrypoint: npm run start
