version: "3.8"
services:
  ikcv:
    image: ikcv-dev:${TAG:-latest}
    build: 
      context: .
      dockerfile: Dockerfile.Development
    container_name: ikcv-dev
    ports:
      - "4200:4200"
    volumes:
      - type: bind
        source: ./
        target: /app
<<<<<<< HEAD
    entrypoint: npm run start
=======
    entrypoint: bash -c "npm i && npm run start"
>>>>>>> dev
